### ISSUE TITLE
Store.Mongodb data error

### ISSUE THREAD

**Issue by fehimismailov** [ysocorp/koa2-ratelimit#14]
If you use the Mongodb store to persist the rate limits, X-RateLimit-Remaining and X-RateLimit-Reset headers are set as NaN because of the bug with the function below. 

`   async incr(key, options, weight) {
        await this._removeAll();
        const data = await this.Ratelimits.findOrCreate({
            where: { key },
            defaults: {
                key,
                dateEnd: Date.now() + options.interval,
            },
        });
        await this._increment(this.Ratelimits, { key }, weight, 'counter');
        return {
            counter: data.counter + weight,
            dateEnd: data.dateEnd,
        };
    }`

The data object has a key *value* where the counter and dateEnd are listed. The return object should return 
`return {
            counter: data.value.counter + weight,
            dateEnd: data.value.dateEnd,
        }`
instead of 
`return {
            counter: data.counter + weight,
            dateEnd: data.dateEnd,
        }`

**Comment by jeanclaudeyalap** [comment]
Thanks, i fix it on commit https://github.com/ysocorp/koa2-ratelimit/commit/5082dd906d03ec907bf613c135d412d217a2e0fb
