### ISSUE TITLE
Mongoose Store not working

### ISSUE THREAD

**Issue by tanekim77** [ysocorp/koa2-ratelimit#3]
store: new Stores.MongodbStore(mongoose.Connection, {
            collectionName: "ratelimits",
            collectionAbuseName: "ratelimitabuses"
          })

throws an error:
 UnhandledPromiseRejectionWarning: TypeError: Stores.MongodbStore is not a constructor

**Comment by tanekim77** [comment]
never mind, the issue was that my mongodb was not running at that time.

**Comment by jeanclaudeyalap** [comment]
I made a mistake in the example use, `new Stores.Mongodb` instead of `new Stores.MongodbStore`

**Comment by jeanclaudeyalap** [comment]
Fix Readme on https://github.com/ysocorp/koa2-ratelimit/commit/ca3e3227b0990100aefb05ddf61489c971382073.

Please close this issue and open an other for `support native Mongodb`
