### ISSUE TITLE
Redis package

### ISSUE THREAD

**Issue by kuselan84** [ysocorp/koa2-ratelimit#37]
promise-redis breaks if redis@next installed along. promise-redis is not needed as node-redis v4 support natively.

**Comment by petersg83** [comment]
promise-redis v4 is @latest now, so it breaks for me too

**Comment by 007tom** [comment]
try this: `npm i redis@3.1.2`
and run `npm list redis`

You will find that `redis` in `promise-redis` is **deduped** with 3.1.2

It works for me (this is a temporary solution).

**Comment by alexandrebodin** [comment]
We also need this to be fixed asap on our side it's breaking our lib depending on it for a lot of users

**Comment by 007tom** [comment]
Yes, pr #38 should fix this for all user.

**Comment by julienwilmet** [comment]
The pr is merged, I will update the package shortly.

Let me know if you run in more issues

**Comment by petersg83** [comment]
Thank you for your quick reaction! It is highly appreciated 😊
