### ISSUE TITLE
Redis Store Feature request

### ISSUE THREAD

**Issue by tanekim77** [ysocorp/koa2-ratelimit#4]
Express version supports Redis Store.
I would highly appreciate if you can make this support Redis store as well.
Thanks!

**Comment by ashokvishwakarma** [comment]
Merge https://github.com/ysocorp/koa2-ratelimit/pull/9

**Comment by jeanclaudeyalap** [comment]
@ashokvishwakarma  Thanks, I published it in the version 0.7.0
