### ISSUE TITLE
Marking peer dependencies as optional

### ISSUE THREAD

**Issue by alexandrebodin** [ysocorp/koa2-ratelimit#47]
## 🚀  Feature request
When using this package with one of the providers you will always get peerDependencies warnings because you won't be using all possible providers at once. 

With npm v7+ `peerDependenciesMeta` were introduced to mark peerDependencies as optional. In this package I think it would be a quick win to avoid the npm warnings and make everyone happy :) 

Happy to make a PR if someone is ready to merge it and release :)

**Comment by julienwilmet** [comment]
Hi @alexandrebodin!

You can make a PR, I'll test it on a few existing projects.

How does it work with npm versions < 7?

**Comment by alexandrebodin** [comment]
Hi, 

the peerDependenciesMeta behavior is unchanged for older versions. Npm doesn't know about it and ignores the key.
